pjrt compiled but error on runtime

diff --git a/pjrt-runner/Makefile b/pjrt-runner/Makefile
--- a/pjrt-runner/Makefile
+++ b/pjrt-runner/Makefile
@@ -7,9 +7,17 @@ pjrt_runner: $(SRC_DIR)/pjrt_runner.c
 		echo "Error: Set XLA_SOURCE_DIR=/path/to/xla, e.g. make XLA_SOURCE_DIR=... pjrt_runner"; \
 		exit 1; \
 	fi
-	
+
 	mkdir -p $(BUILD_DIR)
 	$(CC) $(CFLAGS) -I $(XLA_SOURCE_DIR) $< -ldl -o $(BUILD_DIR)/$@
+
+make run_pjrt_runner: pjrt_runner
+	@if [ -z "$(PJRT_GPU_SO)" ] || [ -z "$(MORSE_MLIR)" ]; then \
+		echo "Error: Set PJRT_GPU_SO=/path/to/pjrt_c_api_{cpu|gpu}_plugin.so and MORSE_MLIR=/path/to/morse/mlir/source"; \
+		exit 1; \
+	fi
+
+	$(BUILD_DIR)/pjrt_runner $(MORSE_MLIR) $(PJRT_GPU_SO)
 
 clean:
 	rm -rf $(BUILD_DIR)
